ACP2E-1122: [Documentation] "Allow Multiple Boxes for Shipping" is visible only "Qty Uses Decimals" is set to Yes.
AdobeDocs/commerce-admin.en pull request #6
Opened 2022-08-30 22:00 UTC by vkolesny

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

As per https://jira.corp.adobe.com/browse/ACP2E-992 we need to update the documentation.

"Allow Multiple Boxes for Shipping" is visible only when "Qty Uses Decimals" is set to Yes.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

- Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- No.

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- No.

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/configuration.html
- https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/product-options.html

2022-08-30 23:09 UTC, leslietilling requested changes
Minor edits and add ExL tags to UI labels for localization support.

2022-08-30 23:09 UTC, leslietilling commented on help/inventory-management/configuration.md
> +| [!UICONTROL Allow Multiple Boxes for Shipping] | Determines if parts of a product can be shipped separately. Is visible when **Qty Uses Decimals** = `Yes`. |
```suggestion
| [!UICONTROL Allow Multiple Boxes for Shipping] | Determines if parts of a product can be shipped separately. This option is visible when **[!UICONTROL Qty Uses Decimals]** = `Yes`. |
```

2022-08-30 23:09 UTC, leslietilling commented on help/inventory-management/product-options.md
> +1. Set **[!UICONTROL Allow Multiple Boxes for Shipping]** to `Yes` if the product can be sold separately, in many boxes. This option is visible when **Qty Uses Decimals** is set to `Yes` only.
```suggestion
1. Set **[!UICONTROL Allow Multiple Boxes for Shipping]** to `Yes` if the product can be sold separately, in many boxes. This option is visible when **[!UICONTROL Qty Uses Decimals]** is set to `Yes` only.
```

2022-08-30 23:09 UTC, leslietilling commented on help/inventory-management/product-options.md
> +| [!UICONTROL Allow Multiple Boxes for Shipping] | Global | Determines if parts of the product can be shipped separately. Is visible when **Qty Uses Decimals** = `Yes`. |
```suggestion
| [!UICONTROL Allow Multiple Boxes for Shipping] | Global | Determines if parts of the product can be shipped separately. This option is visible when **[!UICONTROL Qty Uses Decimals]** = `Yes`. |
```

2022-08-31 15:25 UTC, vkolesny commented on help/inventory-management/configuration.md
> +| [!UICONTROL Allow Multiple Boxes for Shipping] | Determines if parts of a product can be shipped separately. Is visible when **Qty Uses Decimals** = `Yes`. |
done

2022-08-31 15:25 UTC, vkolesny commented on help/inventory-management/product-options.md
> +1. Set **[!UICONTROL Allow Multiple Boxes for Shipping]** to `Yes` if the product can be sold separately, in many boxes. This option is visible when **Qty Uses Decimals** is set to `Yes` only.
done

2022-08-31 15:25 UTC, vkolesny commented on help/inventory-management/product-options.md
> +| [!UICONTROL Allow Multiple Boxes for Shipping] | Global | Determines if parts of the product can be shipped separately. Is visible when **Qty Uses Decimals** = `Yes`. |
done

2022-08-31 15:26 UTC, vkolesny commented
Minor edits were successfully added.

2022-08-31 16:06 UTC, leslietilling approved these changes

2022-08-31 20:32 UTC, merged