remove MSI
AdobeDocs/commerce-admin.en pull request #7
Opened 2022-09-02 22:06 UTC by ejaz-alam

2022-09-19 19:22 UTC, leslietilling requested changes
@ejaz-alam  Minor edit on the intro sentence. Can we also add a sentence about why someone would want to remove the modules? Are there any negative consequences to this?

2022-09-19 19:22 UTC, leslietilling commented on help/inventory-management/install-update.md
> +Inventory Management moudule can be remove through composer file. To remove all MSI module simply add the following into composer.json
```suggestion
Inventory Management module can be remove through composer file. To remove all Inventory Managements modules, simply add the following into composer.json.
```

2022-09-19 19:51 UTC, ejaz-alam commented
> @ejaz-alam Minor edit on the intro sentence. Can we also add a sentence about why someone would want to remove the modules? Are there any negative consequences to this?

so sometimes we do not use the inventory modules and these modules are more than 20 modules which really affects the performance. so in terms performance, it could be uninstalled.

2022-09-20 18:54 UTC, leslietilling approved these changes
I am approving here and must then import to our internal repo, where I will make some minor grammatical and syntax edits before merging.

2022-09-21 15:20 UTC, merged